name: "Font Project Configuration"
description: "Set up font project build configuration"
inputs:
  projectname: # id
    description: "Typeface family name (optional, default='Font')"
    required: false
    default: "Font"
  sourcepath: # id
    description: "Path to source file directory relative to root (optional, default='src')"
    required: false
    default: "src"
  buildpath: # id
    description: "Path to build file directory relative to root (optional, default='build')"
    required: false
    default: "build"
  licensepath: # id
    description: "Path to project license relative to root (optional, default='None')"
    required: false
    default: "None"
  readmepath: # id
    description: "Path to project README file relative to root (optional, default='README.md')"
    required: false
    default: "README.md"
  changelogpath: # id
    description: "Path to project changelog relative to root (optional, default='CHANGELOG.md')"
    required: false
    default: "CHANGELOG.md"
  py-version: # id
    description: "The Python interpreter version (optional)"
    required: false
    default: "3.8.2"
  dependpath: # id
    description: "Path to build dependency definitions requirements.txt file (optional, default='requirements.txt')"
    required: false
    default: "requirements.txt"
  dev-dependpath: # id
    description: "Path to developer dependency definitions requirements.txt file (optional, default='dev-requirements.txt')"
    required: false
    default: "dev-requirements.txt"
  buildcommand: # id
    description: "The build command to produce font artifacts"
    required: false
    default: "make"
outputs:
  projectname:
    description: "Typeface family name"
  sourcepath: # output will be available to future steps
    description: "path to source file directory relative to root"
  buildpath:
    description: "path to build file directory relative to root"
  licensepath: # id
    description: "Path to project license"
  readmepath: # id
    description: "Path to project README file"
  changelogpath: # id
    description: "Path to project changelog"
  py-version:
    description: "The Python interpreter version"
  dependpath: # id
    description: "Path to build dependency definitions requirements.txt file"
  dev-dependpath: # id
    description: "Path to developer dependency definitions requirements.txt file"
  buildcommand: # id
    description: "The build command to produce font artifacts"
runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "type"
  color: "purple"
