name: "Font Project Configuration"
description: "Set up font project build configuration"
inputs:
  projectname: # id
    description: "Typeface family name"
    required: false
    default: "Font"
  sourcepath: # id
    description: "Path to source file directory relative to root"
    required: false
    default: "src"
  buildpath: # id
    description: "Path to build file directory relative to root"
    required: false
    default: "build"
  licensepath: # id
    description: "Path to project license relative to root"
    required: false
    default: "None"
  readmepath: # id
    description: "Path to project README file relative to root"
    required: false
    default: "README.md"
  changelogpath: # id
    description: "Path to project changelog relative to root"
    required: false
    default: "CHANGELOG.md"
  py-version:
    description: "The Python interpreter version"
    required: false
    default: "3.8.2"
outputs:
  projectname:
    description: "Typeface family name"
  sourcepath: # output will be available to future steps
    description: "path to source file directory relative to root"
  buildpath:
    description: "path to build file directory relative to root"
  licensepath: # id
    description: "Path to project license"
  readmepath: # id
    description: "Path to project README file"
  changelogpath: # id
    description: "Path to project changelog"
  py-version:
    description: "The Python interpreter version"
runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "type"
  color: "purple"
